# .github/workflows/my-workflow.yml
on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-

      - name: Echo secret
        run: echo ${{ vars.CONFLUENCE_CLOUD_ID }}

      - name: remove first line 
        run:  cat ./README.md | tail -n +2 > ./CUT_README.md

      - uses: cupcakearmy/confluence-markdown-sync@v1
        with:
          from: './CUT_README.md'
          to: '23396353' # The confluence page id where to write the output
          cloud: ${{ vars.CONFLUENCE_CLOUD_ID }}
          user: ${{ vars.CONFLUENCE_CLOUD_EMAIL }}
          token: ${{ secrets.CONFLUENCE_CLOUD_TOKEN }}