# .github/workflows/my-workflow.yml
on: [push]

jobs:
  dev:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
            restore-keys: |
              ${{ runner.os }}-pip-

      - name: Echo secret
        run: echo ${{ env.CONFLUENCE_CLOUD_ID }}

      - uses: cupcakearmy/confluence-markdown-sync@v1
        with:
          from: './README.md'
          to: '23396353' # The confluence page id where to write the output
          cloud: ${{ secrets.CONFLUENCE_CLOUD_ID }}
          user: ${{ env.CONFLUENCE_CLOUD_EMAIL }}
          token: ${{ env.CONFLUENCE_CLOUD_TOKEN }}