name: Main Semantic Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/workflows/codeql.yml"
  pull_request:
    branches:
      - main

jobs:
  release_semantic:
    name: Release Semantic
    if: ${{ github.event_name == 'push' &&  github.ref_name == 'main' }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          token: ${{ github.token }}
          # persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version-file: '.nvmrc'

      - name: Install Dependencies
        run: npm install    

      - name: Run release
        id: release
        env:
          GH_TOKEN: ${{ github.token }}
          NPM_TOKEN: ${{ github.token }}
          GIT_AUTHOR_NAME: semantic-release-akfdev-com
          GIT_AUTHOR_EMAIL: semantic-release-bot@akfdev.com
          GIT_COMMITTER_NAME: semantic-release-bot-akfedv-com
          GIT_COMMITTER_EMAIL: semantic-release-bot@akfdev.com
        run: |
          npm config set registry https://npm.pkg.github.com/
          npm config set //npm.pkg.github.com/:_authToken $GH_TOKEN
          npx semantic-release


