name: Submit Extension

on:
  push:
    branches:
      - main

jobs:
  submit_extension:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

      - name: Build Extension
        run: yarn archive

      # https://github.com/marketplace/actions/browser-platform-publisher
      - name: Submit Extension
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.BPP_KEYS }}
          chrome-file: "chrome/myext_chromium_${{ env.EXT_VERSION }}.zip"
          edge-file: "edge/myext_edge_${{ env.EXT_VERSION }}.zip"
          edge-notes: "This is a test submission"
          version-file: "src/manifest.json"
          verbose: true
